### ISSUE TITLE
Faulty Lava Gen

### ISSUE THREAD

**Issue by DarianLStephens** [Tesseract4D/GregCaves#3]
I tried raising the lava to obscure the flat floor, but it generates in patches rather than a smooth surface across the entire world.
![2024-08-18_23 40 22](https://github.com/user-attachments/assets/aefc77f9-96e3-4ab3-9200-f51ac22371b7)
![2024-08-18_23 40 48](https://github.com/user-attachments/assets/88c7db4f-41a0-4392-8423-966edf409cae)

**Comment by Tesseract4D** [comment]
will fix later

**Comment by DarianLStephens** [comment]
If it helps, it looks like it's only generating in vanilla caves, or where they would be cutting through the big caves.
